---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
before_install: gem update --system
jobs:
  include:
    - stage: gem release
      rvm: 2.3
      script: echo "Deploying to rubygems.org ..."
      deploy:
        provider: rubygems
        gem: open_code-rails
        api_key: $RUBYGEMS_API_KEY
        on: release
