---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
before_install: gem install bundler -v '~> 1.17.3'
jobs:
  include:
    - stage: gem release
      rvm: 2.3
      script: echo "Deploying to rubygems.org ..."
      deploy:
        provider: rubygems
        gem: open_code-rails
        api_key: $RUBYGEMS_API_KEY
        on: release
